server {
    listen       80;
    server_name  _;
    charset      utf-8;          # กันภาษาไทย/สัญลักษณ์เพี้ยน
    root   /usr/share/nginx/html;
    index  index.html;

    # ธนาคารกำหนด: ต้องตรวจสอบ version ที่ deploy ได้
    location = /version {
        default_type application/json;
        try_files /version.json =404;
    }

    # ใช้เป็น health check ของ pipeline
    location = /healthz {
        access_log off;
        default_type text/plain;
        return 200 "ok\n";
    }

    location / {
        try_files $uri $uri/ =404;
    }

    gzip on;
    gzip_types text/css application/javascript image/svg+xml;
}
